# Modelo con dos bienes, gobierno y producción

## Gobierno

Como en el caso anterior, introducimos un gobierno que consume ambos bienes. Denotamos con $g_{Ts}$ la cantidad de bienes comerciables que consume el gobierno en el periodo $s$ y equivalentemente $g_{ns}$ la cantidad de bienes no comerciables que consume el gobierno en el periodo $s$. Luego, el gobierno debe satisfacer la siguiente restricción presupuestal,

$$
g_{Ts} + p_s g_{ns} = p_s \tau_s + b_{s+1} - (1 + r_{s-1})b_s
$$
Para cada $s \geq t$. Iterando hacia adelante a partir del periodo $s$ se obtiene que 

$$
\sum_{j\geq s} \Delta_j (g_{Tj}+p_jg_{nj}) = -(1+r_{s-1})b_s + \sum_{j \geq s} \Delta_j p_j \tau_j
$$


## Problema de optimización 

En este caso, el agente representativo busca,

$$
\begin{align}
\max_{c_{Ts}, c_{ns}, b_{s+1}, s\geq t}  \sum_{s\geq t}\beta^{s-t}\ln(c_s) \\
 c_s &= c_{Ts}^\gamma c_{ns}^{1-\gamma} \\
c_{Ts} + p_sc_{ns} + p_s \tau_s + b_{t+1} &= y_{Ts} + p_sy_{ns} + (1 + r_{s-1})b_s
\end{align}
$$

Ahora la principal diferencia es que los bienes son producidos; es decir, $y_{Ts} = A_sF(L_{Ts})$ y $y_{ns} = G(L_{ns})$, donde $L_i$ es la cantidad de horas trabajadas en el sector $i \in {Ts, ns}$. Se asume que las ofertas de trabajo anteriores son completamente inelásticas en cada periodo $s$; además, notacionalmente $L_s = L_{Ts} + L_{ns}$. La funciones de producción son crecientes a tasas decrecientes (es decir, $F' > 0, F''<0, G' > 0, G''<0$). 

En este caso están dados $\{L_{Ts}, L_{ns}, g_{Ts}, g_{ns}, r_{s-1}\}_{s\geq t}$, $d_t$ y $b_t$. Sustituyendo la restricción presupuestal del gobierno en la restricción del agente representativo obtenemos que,

$$
c_{Ts} + p_s c_{ns} + g_{Ts} + p_s g_{ns}+b_{t+1}-d_{t+1} = A_sF(L_{Ts}) + p_sG(L_{ns})+(1+r_{s-1})(b_s-d_s)
$$

En este caso la condición de vaciado del mercado de bienes no comerciables es

$$
c_{ns} = y_{ns} - g_{ns} = A_sF(L_{Ts}) - g_{ns}
$$
Por lo que la balanza comercial está dada por,

$$
T_s = y_{Ts} - c_{Ts}-g_{Ts} = A_sF(L_{Ts}) - c_{Ts} - g_{Ts}
$$
Y la cuenta corriente está dada por,

$$
CA_s = (b_{s+1}-d_{s+1})-(b_s-d_s) = T_s + r_{s-1}(b_s-d_s)  = y_{T_s} - c_{Ts}-g_{Ts} + r_{s-1}(b_s-d_s)
$$
## Condiciones de primer orden

Dado que las ofertas laborales son completamente inelásticas, las condiciones de primer orden son similares a modelo anterior. De este modo, se tiene que para cualquier $s \geq t$,

$$
c_{T(s+1)} = \beta(1+r_{s-1})c_{Ts}
$$
Además,

$$
p_s = \frac{(1-\gamma) c_{Ts}}{\gamma c_{ns}}
$$
Además de lo anterior, se deben verificar las conficiones de optimalidad del mercado laboral, dado que las empresas maximizan ganancias. Se asume un mismo salario para los sectores comerciables y no comerciables de $w_s$ para cada $s \geq t$; por lo tanto, en equilibrio, para cada $s \geq t$,

$$
w_s = A_{Ts}F'(L_{Ts}) = p_s G'(L_{ns})
$$
En este caso, tenemos dos condiciones de vaciado. Para el mercado de bienes no comerciables,

$$
c_{ns} = y_{ns} - g_{ns}
$$

Para cada $s \geq t$. Y para el mercado laboral,

$$
L_{Ts} + L_{ns} = L_s
$$
Para cada $s \geq t$.

## Restricción presupuestal

Considerando la condición de vaciado de mercado e iterando la restricción presupuestal hacia adelante, resulta que para cada $s\geq t$,

$$
\sum_{j\geq s}\Delta_jT_j = -(1+r_{s-1})(b_s-d_s)
$$

O bien, 

$$
\sum_{j\geq s}\Delta_j c_{Tj} = (1+r_{s-1})(b_s-d_s) + \sum_{j \geq s}\Delta_j (A_jF(L_{Tj}) - g_{Tj})
$$
## Solución

Sabemos que $A_{Ts}F'(L_{Ts}) = p_sG'(L-L_{Ts})$ para cada $s \geq t$. Por lo tanto, la oferta laboral óptima es una función de $p_s$ y $A_{Ts}$; es decir, 
$$
L_{Ts} = l(p_s(-), A_{Ts}(+))
$$

Esta función es homogénea de grado cero en su argumento. Por lo tanto,

$$
y_{Ts} = y_T(p_s(-), A_{Ts}(+))
$$ 

Que es homogénea de grado uno en su argumento y 

$$
y_{ns} = y_n(p_s(+), A_{Ts}(-))
$$ 

Que es homogénea de grado cero. Siguiendo las condiciones de primer orden, se verifica que

$$
\frac{p_{s+1}}{p_s} = \frac{c_{T(s+1)}c_{ns}}{c_{Ts}c_{n(s+1)}} = \beta(1+r_s)\frac{c_{ns}}{c_{n(s+1)}}
$$
Lo último utilizando la condición de euler. Así, con la condición de vaciado del mercado de bienes no comerciables se tiene que,

$$
\frac{p_{s+1}}{p_s} = \beta(1+r_s)\frac{y_{n}(p_s, A_{Ts}) - g_{ns}}{y_{n}(p_{s+1}, A_{T(s+1)}) - g_{n(s+1)}} 
$$

La anterior, es la solución implícita de la ecuación en diferencias de $p_s$. Por otro lado, a partir de la ecuación de euler para los bienes comerciables se obtiene que para cada $s \geq t$ y $j \geq s$,

$$
\Delta_j c_{Tj} = \beta^{s-j}c_{Ts}
$$

Por lo tanto, para cada $s \geq t$, 

$$
c_{Ts} = (1-\beta)(1+r_{s-1})(b_s - d_s) + \widehat{y_T(p_s, A_{Ts})} - \widehat{g_{Ts}}
$$

## Supuestos habituales

Si $r_{s-1} = r^*$ para cada $s \geq t$ y $\beta(1 + r^*) = 1$ entonces, por la condición de euler, el consumo de bienes comerciables es el mismo en todos los periodos y 

$$
c_T = c_{Ts} = r^*(b_s-d_s) + \widehat{y_T(p_s, A_{Ts})} - \hat{g_{Ts}}
$$

En este caso, la cuenta corriente está dada por,

$$
CA_s = (y_T(p_s, A_{Ts}) - \widehat{y_T(p_s, A_{Ts})}) - (g_{Ts}-\hat{g_{Ts}})
$$

## Ejemplo

Supongamos que $r_{s-1} = r^*$ para cada $s \geq t$ y $\beta(1 + r^*) = 1$. Además, supongamos que $A_T = A_{Ts} = A_{T(s+1)}$ para cada $s \geq t$. Bajo estas condiciones se verifica que,

$$
p_sG'(L-L_{Ts}) = A_TF'(L_{Ts})
$$

Por lo tanto, $p_0 = p_s = p_{s+1}$ para cada $s \geq t$. De lo anterior se sigue que la producción de bienes no comerciables y comerciables es la misma para todos los periodos; es decir, 

$$
y_{T}(p_0, A_T) = y_T(p_s, A_{Ts}) 
$$

Para cada $s \geq t$. Y,

$$
y_{n}(p_0, A_T) = y_n(p_s, A_{Ts})
$$

Para cada $s \geq t$. Por lo anterior, se verifica que,

$$
c_{Ts} = c_T = r^*b_t + y_T(p_0, A_T) - \widehat{g_{Ts}}
$$

Y además,

$$
c_{ns} = c_n = y_n(p_0, A_T) - g_{ns}
$$

Obsérvese que con lo anterior, necesariamente $g_{ns} = g_n$ para cada $s \geq t$. Así, se tiene que,

$$
p_0 = \frac{(1-\gamma)c_T}{\gamma c_n} = \frac{(1-\gamma)(r^*b_t + y_T(p_0, A_T)-\widehat{g_{T_s}})}{\gamma(y_n(p_0, A_T)-g_n)} 
$$

De donde se obtiene implícitamente el valor de $p_0$. 

### Choque en la productividad

Supongamos que $A_{Ts} = \lambda A_T$ para cada $s \geq t$ y $\lambda >1$. Luego, si $b_t = g_{Ts} = g_{n_s} = 0$ para cada $s \geq t$, se tiene que,

$$
p_0 = \frac{(1-\gamma)y_T(p_0, A_T)}{\gamma y_n(p_0, A_T)} = \lambda^{-1} \frac{(1-\gamma)y_T(\lambda p_0, \lambda A_T)}{\gamma y_n(\lambda p_0, \lambda A_T)} = \lambda^{-1} p_1
$$

Así, $p_1 = \lambda p_0$, por la homogeneidad de las funciones.