# Modelo con un solo bien, dotación, gobierno y dinero

## Gobierno

La restricción presupuestal del gobierno está dada por,

$$
P_s g_s = P_s \tau_s + M_s - M_{s-1} + D_{s+1} - D_s(1+R_{s-1})
$$
Donde $M_s$ es la cantidad nominal de dinero.

## Problema de optimización 

En este caso, el agente representativo busca,

$$
\begin{align}
\max_{c_{s}, m_s, B_{s+1}, B^*_{s+1}, s\geq t}  \sum_{s\geq t}\beta^{s-t}\left(\ln(c_s) + \eta \ln\left(\frac{m_s}{P_s}\right) \right) \\
P_sc_{s} + B_{s+1} + \varepsilon_s B^*_{s+1} + m_s + P_s \tau_s &= P_s y_{s} + (1 + R_{s-1})B_s + \varepsilon_{s} (1 + R^*_{s-1})B^*_s + m_{s-1}
\end{align}
$$

Donde ahora $B_s$ es el valor nominal de lo bonos nacionales y $B^*_s$ es el valor nominal de los bonos adquiridos en el extranjero. Ademas, $\varepsilon_s$ es el tipo de cambio en el periodo $s \geq t$; es decir,

$$
\varepsilon_s = \frac{P_s}{P^*_s}
$$

Además, $m_s$ es la cantidad de dinero que el agente demanda. Se define la condición de paridad descubierta de las tasas de interés como,

$$
1+R_s = (1+R^*_s)\frac{\varepsilon_{s+1}}{\varepsilon_s}
$$
Se define, además, 

$$
1 + r_s = (1+R^*_s)\frac{P^*_s}{P^*_{s+1}} 
$$
Esta tasa de interés real es la misma a nivel mundial. Además, se verifica por la paridad descubierta de las tasas de interés y de la definición de tipo de cambio que,

$$
1 + r_s = (1+R_s)\frac{P_s}{P_{s+1}}
$$
Observemos además que,

$$
\frac{(1+R_{s-1})B_s}{P_{s}} = \frac{(1+R_{s-1})B_sP_{s-1}}{P_{s}P_{s-1}} = (1+r_s)b_s
$$

Lo anterior también se cumple para $D_t$. Observemos además, que

$$
\frac{\varepsilon_{s} (1 + R^*_{s-1})B^*_s}{P_{s}} = \frac{(1 + R^*_{s-1})B^*_s}{P^*_{s}} = \frac{(1+R^*_{s-1})B^*_sP^*_{s-1}}{P^*_{s}P^*_{s-1}} = (1+r_s)b^*_s
$$

Definimos $a_s = b^*_s$, para cada $s\geq t$. En este caso, la balanza comercial está dada por,

$$
T_s = y_{s} - c_{s}-g_{s} 
$$

En tanto que, usando la condición de vaciado del mercado de dinero $M_s = m_s$,7 la cuenta corriente está dada por,

$$
CA_s = (a_{s+1} -a_s) + (b_{s+1}-b_{s})-(d_{s+1}-d_s) = T_s + r_{s-1}(a_s + b_s-d_s)  = y_{s} - c_{s}-g_{s} + r_{s-1}(a_s + b_s-d_s)
$$

## Condiciones de primer orden

### Bonos

A partir de las condiciones de primer orden se verifica la condición de paridad descubierta de las tasas de interés,

$$
1 + R_s =   (1 + R^*_s)\frac{\varepsilon_{s+1}}{\varepsilon_s}
$$

Para cada $s \geq t$.

### Intertemporal

Para cada $s \geq t$, se verifica que

$$
P_{s+1}c_{s+1} = \beta (1+R_s)P_s c_s
$$

Usando la paridad descubierta de las tasas de interés y la ley de un solo precio, se verifica que

$$
c_{s+1} = \beta(1+r_s)c_s
$$

¡La ecuación de euler habitual!

### Monetaria

La condición de optimalidad es la siguiente:

$$
\eta c_s = \left(1-\frac{1}{1+R_s}\right) \frac{m_s}{P_s} = \left(1-\frac{1}{1+R_s}\right) z_s
$$

Recordemos que,

$$
1 + R_s = (1+r_s)\frac{P_{s+1}}{P_{s}} = (1+r_s)\frac{M_{s+1}}{M_s}\frac{z_{s}}{z_{s+1}}
$$
Por lo tanto, en equilibrio,

$$
\eta c_s = \left(1-\frac{1}{1+r_s}\frac{M_{s}}{M_{s+1}}\frac{z_{s+1}}{z_{s}}\right) z_s
$$
Despejando $z_{s+1}$ obtenemos que,

$$
\left(\frac{1}{1+r_s}\frac{M_s}{M_{s+1}}\right)z_{s+1} = z_s - \eta c_s
$$

Que es una ecuación de diferencias en $z_s$ de orden uno.

### Vaciado de dinero

En el óptimo, se debe verificar que

$$
M_s = m_s
$$

Para cada $s \geq t$.

## Restricción presupuestal

Considerando la condición de vaciado de mercado e iterando la restricción presupuestal hacia adelante, resulta que para cada $s\geq t$,

$$
\sum_{j\geq s}\Delta_jT_j = -(1+r_{s-1})(a_s + b_s-d_s)
$$

O bien, 

$$
\sum_{j\geq s}\Delta_j c_{j} = (1+r_{s-1})(a_s + b_s-d_s) + \sum_{j \geq s}\Delta_j (y_j - g_{j})
$$

## Solución

### Sector real de la economía

A partir de la ecuación de euler se verfifica que para cada $s \geq t$ y cada $j \geq s$,

$$
\Delta_j c_j = \beta^{j-s} \Delta_s c_s
$$
Por lo que, en equilibrio, el valor del consumo en el periodo $s$ está dado por,

$$
c_s = (1-\beta)(1 + r_{s-1})(a_s + b_s-d_s) + \hat{y_s} - \hat{g_s}
$$
### Sector monetario de la economía

Conociendo $c_s$ para cada $s \geq t$, se tiene que,

$$
\left(\frac{1}{1+r_s}\frac{M_s}{M_{s+1}}\right)z_{s+1} = z_s - \eta c_s
$$

## Supuestos habituales

Si $r_{s-1} = r$ para cada $s \geq t$ y $\beta(1+r) = 1$ entonces, para la parte real,

$$
c = c_s = r(a_t + b_t-d_t) + \hat{y_t} - \hat{g_t}
$$
En tanto que para la parte monetaria,

$$
\left(\beta\frac{M_s}{M_{s+1}}\right)z_{s+1} = z_s - \eta c_s
$$

Si $M_{s+1} = (1+\hat{M})M_s$ para cada $s \geq t$ entonces,

$$
\frac{\beta}{1+ \hat{M}}z_{s+1} = z_s - \eta c_s
$$

Cuya solución es 

$$
z = z_s = \left(1-\frac{\beta}{1+\hat{M}}\right)^{-1}\eta c
$$

Como se tiene que,

$$
\eta c_s = \left(1-\frac{1}{1+R_s}\right) z_s
$$

Entonces, 

$$
1 + R_s = 1+ R = \frac{1+\hat{M}}{\beta}
$$
Utilizando la ley de un solo precio, llegamos a que,

$$
\varepsilon_s = \frac{P_s}{P^*_s} = \frac{1}{P^*_s} \frac{M_s}{z_s} = \frac{1}{P^*_s}\frac{M_t(1+\hat{M})^{s-t-1}(1+\hat{M}-\beta)}{\eta c}
$$

