#Introducción

En este documento se exponen los modelos utilizados en la clase de Economía Interacional II. Se omiten alunos detalles algebraicos y en todos ellos se utiliza un agente representativo.

## Convenciones

A lo largo de los caítulos se utilizan las siguientes convenciones:

- Se utiliza $t$ para denotar al periodo presente.
- Se utiliza $s$ para denotar un periodo arbitrario.
- Se utiliza $h$ para denotar un número de periodos arbitrario.

Además se utiliza la siguiente notación:

$$
\sum_{s = t}^\infty x_s = \sum_{s \geq t} x_s
$$
Para cualquier variable $x_s$.

<!--chapter:end:index.Rmd-->

#Modelo con un solo bien y con dotación

##Problema de optimización

En este modelo en la economía existe un solo bien. En cada periodo la cantidad que consume el agente representativo se denota con $c_s$ para $s\geq t$. El objetivo del agente representativo es

$$
\max_{c_s, b_{s+1}, s \geq t} \{ \sum_{s\geq t} \beta^{s-t}\ln(c_s):  c_s + b_{s+1} = y_s + (1+r_{s-1})b_s, s \geq t\}
$$
En donde $b_s$ denota la cantidad del bien que el agente representativo ahorra en el periodo $s$, $y_s$ la dotación del bien en el periodo $s$ y $r_s$ la tasa de interés del periodo $s$. Además, en este problema están dados $\{y_s, r_{s-1}\}_{s\geq t}$ y $b_t$. 

Por otro lado, se define

$$
T_s = y_s- c_s
$$
La balanza comercial del país en el periodo $s$ y además

$$
CA_s = b_{s+1} - b_s = T_s + r_{s-1}b_s
$$
La cuenta corriente del país en el periodo $s$. La identidad anterior surge de la restricción presupuestal del agente representativo.  

## Condiciones de primer orden

De las condiciones de primer orden se obtiene la siguiente condición de optimalidad, conocida como la ecuación de euler,

$$
c_{s+1} = \beta(1+r_s)c_s
$$
Para cada $s \geq t$.

## Restricción presupuestal 

Para $s \geq t$ y $j \geq s$ definimos $\Delta_j$ como $\Delta_j = 1$ si $j = s$ y 

$$
\Delta_j = \prod_{k = s}^{j-1} \frac{1}{1+r_k}
$$
Para $j \geq s + 1$. Iterando hacia adeltante con la restricción presupuestal del agente representativo a partir del periodo $s$ se obtiene que en el óptimo,

$$
\sum_{j\geq s} \Delta_jT_j = -(1+r_{s-1})b_s 
$$
O bien,

$$
\begin{equation}
\sum_{j\geq s} \Delta_jc_j = (1+r_{s-1})b_s  + \sum_{j\geq s} \Delta_jy_j
(\#eq:rp)
\end{equation}  
$$

*En particular* para el periodo $t$ se verifica que,

$$
\sum_{s \geq t} \Delta_s c_s = (1+r_{t-1})b_t + \sum_{s \geq t} \Delta_s y_s
$$b_
Con lo anterior estamos listos para establecer resultados a partir de supuestos sobre las variables dadas. Pero antes enunciemos un **resultado fundamental**.

##Solución 

De la ecuación de euler sabemos que $c_{s+1} = \beta(1+r_s)c_s$ para cada $s \geq t$. Luego, para cada periodo $s \geq t$ y $j \geq s$ se verfifica que,

$$
\begin{align}
\Delta_jc_j &= \Delta_j \beta(1+r_{j-1}) c_{j-1} \\
&= \beta \Delta_{j-1}c_{j-1}
\end{align}
$$
Iterando lo anterior hasta el periodo $s$ obtenemos que,

$$
\Delta_j c_j = \beta^{j-s} \Delta_s c_s
$$

Por lo tanto,

$$
\sum_{j \geq s} \Delta_j c_j = \sum_{j\geq s} \beta^{j-s} \Delta_s c_s = \frac{\Delta_s c_s}{1-\beta}
$$

Sustituyendo la ecuación anterior en \@ref(eq:rp) obtenemos que para cualquier $s \geq t$,

$$
\begin{align}
\Delta_s c_s &= (1-\beta)((1+r_{s-1})b_s + \sum_{j\geq s}\Delta_s y_s) \\
&= (1-\beta)(1+r_{s-1})b_s + (1-\beta)\sum_{j\geq s}\Delta_s y_s \\
&= (1-\beta)(1+r_{s-1})b_s + \hat{y_s}
\end{align}
$$

Donde $\hat{y_s} = (1- \beta)\sum_{j\geq s} \beta^{j-s}y_j$ es el valor permanente de $y$ en el periodo $s$. Como $\Delta_s = 1$ en este caso, esto resuelve el problema pues el consumo para cada periodo $s \geq t$ está dado por,

$$
c_s = (1-\beta)(1+r_{s-1})b_s +\hat{y_s}
$$

Y todos los valores del lado derecho de la igualdad son conocidos. *En particular*, para $s = t$ se tiene que,

$$
\begin{equation}
c_t = (1-\beta)(1+r_{t-1})b_t + \hat{y_t}
(\#eq:cons)
\end{equation}
$$

Este resultado es bastante general pues *se obtuvo a partir de la condición de optimalidad y la restricción presupuestal* **sin hacer supuestos sobre los parámetros del modelo**.

## Supuestos habituales

### Tasa de interés constante

En este caso, se supone que $r_{s-1} = r^*$ para cada $s \geq t$. Por lo que,

$$
\Delta_s = \left(\frac{1}{1 + r^*}\right)^{s-t}
$$

### Consumo constante

Se asume, además de la tasa de interés contante que, $\beta(1+r^*) = 1$. En este caso, $c = c_{s+1} = c_{s}$ para cada $s \geq t$ (a partir de la ecuación de euler). Así, se verifica que

$$
\Delta_s = \beta^{s-t}
$$
Con esto,

$$
\hat{y_s} = (1-\beta)\sum_{j \geq s}\beta^{j-s}y_j
$$
Obsérvese que $(1-\beta)(1+r^*) = 1 + r^* - \beta(1+r^*) = r^*$. Por lo tanto, a partir de \@ref(eq:cons),

$$
c = c_s = r^*b_s + \hat{y_s}
$$

De lo anterior se desprende que la cuenta corriente en el periodo $s$ está determinada por,

$$
CA_s = T_s + r^*b_s =  y_s - c_s + r^*b_s = y_s - \hat{y_s} 
$$

## Ejemplo

Supongamos que $r_{s-1} = r^*$ para cada $s \geq t$ y que $\beta*(1+r^*) = 1$. Además, $y_s = y$ para cada $s\geq t$ y $b_t = 0$. Los dos primeros supuestos establecen que $c = r^*b_t + \hat{y_t}$. Del tercer supuesto se obtiene que 

$$
\hat{y_t} = (1-\beta)\sum_{s\geq t} \beta^{s-t} y_s = (1-\beta)y \sum_{s\geq t} \beta^{s-t} = y
$$

Por lo tanto, usando además el último supuesto, se tiene que $c = c_s = y$ para cada $s \geq t$. Con eso, claramente $T_s = CA_s = 0$ para cada $s\geq t$.

### Choque

Supongamos ahora que hay un choque en la dotación durante $h$ periodos. Formalmente, ahora $y_s = \lambda y$ com $\lambda < 1$ si $t \leq s \leq t+h-1$ y $y_s = y$ para cada $s \geq t+h$ y se mantiene el supuesto de que $b_t = 0$. Recordemos que, en general, se sigue sosteniendo que el consumo es constante y que,

$$
c = r^*b_t + \hat{y_t}
$$

Por lo que basta encontrar el valor permanente de la dotación en $t$. En general, si $t \leq s \leq t+h-1$ entonces,

$$
\begin{align*}
\hat{y_s} &= (1-\beta)\sum_{j \geq s} \beta^{j-s}y_j \\
&= (1-\beta)\left(\sum_{j = s}^{t+h-1}\beta^{j-s}\lambda y + \sum_{j \geq t+h} \beta^{j-s} y\right) \\
& = (1-\beta)\left(\lambda y \sum_{j = s}^{t+h-1}\beta^{j-s} + y \sum_{j \geq t+h} \beta^{j-s }  \right) \\
& = (1-\beta)\left(\frac{1-\beta^{h+(t-s)}}{1-\beta}\lambda y + \frac{\beta^{h+(t-s)}}{1-\beta}y\right) \\
& = \left(1-\beta^{h+(t-s)}\right)\lambda y + \beta^{h+(t-s)} y
\end{align*}
$$

Y si $s \geq t$ entonces $\hat{y_s} = y$. Por lo tanto, $\hat{y_t} = (1-\beta^h)\lambda y + \beta^h y$ y usando que $\beta_t = 0$, se verifica que $c = (1-\beta^h)\lambda y + \beta^h y$. Con esto, para $t \leq s \leq t+h-1$ se sostiente que,

$$
T_s = y_s - c_s = \lambda y - (1-\beta^h)\lambda y - \beta^h y = \beta^h(\lambda - 1)y < 0
$$

Por lo que durante el choque, se importan bienes. En cambio, para $s \geq t+h$ se tiene que ,

$$
\begin{align*}
T_s &= y_s - c_s \\
& = y -(1-\beta^h)\lambda y - \beta^h y \\
& =  (1 - \lambda + \lambda \beta^h  - \beta^h)y \\
& = (1-\lambda)(1-\beta^h)y > 0
\end{align*}
$$

Por lo que tras el choque se exportan bienes. Por el lado de la cuenta corriente, si $t \leq s \leq t+h-1$ entonces

$$
\begin{align*}
CA_s & = y_s - \hat{y_s} \\
& = \lambda y - \left(1-\beta^{h+(t-s)}\right)\lambda y - \beta^{h+(t-s)} y \\
& = \beta^{h +(t-s)}(\lambda-1)y < 0 
\end{align*}
$$

Y si $s \geq t+h$ entonces claramente $CA_s = 0$. Con ,o anterior podemos determinar los niveles de ahorro. Recordemos que $CA_s = T_s + r^*b_s$. Así, para $t \leq s \leq t+h-1$,

$$
\beta^{h +(t-s)}(\lambda-1)y = CA_s = T_s + r^*b_s = \beta^h(\lambda - 1)y + r^*b_s
$$
Por lo tanto, dado que $\frac{1}{r^*} = 1-\beta$

$$
b_s = (1-\beta)\beta^h\left(\beta^{t-s} - 1\right)(\lambda-1)y < 0
$$

Por otro lado, si $s \geq t+h$ entonces, 

$$
0 = CA_s = T_s + r^* b_s = (1-\lambda)(1-\beta^h)y + r^* b_s
$$

Así, en este caso, 

$$
b_s = (1-\beta)(1-\beta^h)(\lambda-1)y < 0
$$
Por lo que en este choque, siempre hay deuda.

### Choque permanente

Supongamos el choque anterior pero de manera permanente. En este caso, $h \rightarrow \infty$, por lo que $b_s, CA_s, T_s \rightarrow 0$ y $c \rightarrow \lambda y$.

<!--chapter:end:01-un-bien-dotacion.Rmd-->

#Modelo con un solo bien, dotación y gobierno


##Gobierno
En este caso el gobierno compra $g_s$ cantidad del bien en la economía para cada $s \geq t$; es decir, la senda de compras del gobierno $\{g_s\}_{s \geq t}$ está dada. Para financiar estas compras, el gobierno establece un impuesto de suma fija $\tau_s$ para cada $s \geq t$ y además se endeuda a la misma tasa a la que el agente representativo presta bonos. Se denota como $d_{s-1}$ para $s \geq t$ la deuda del gobierno con $d_t$ dada. Por lo tanto, la restricción presupuestal del gobierno está dada por

$$
\begin{equation}
g_s = \tau_s + d_{s+1} - (1+r_{s-1})d_s
(\#eq:rpgob)
\end{equation}
$$

Para cada $s \geq t$. El déficit del gobierno es $d_{s+1} -d_s = g_s - \tau_s + r^*d_s$. Además, se verifica que para cada $s \geq t$,

$$
\sum_{j \geq s} \Delta_j g_j = -(1 + r_{s-1})d_s + \sum_{j \geq s} \Delta_j \tau_j 
$$
Es decir, 

$$
\begin{equation}
\hat{g_s} = -(1-\beta)(1+ r_{s-1})d_s + \hat{\tau_s}
(\#eq:rpgobperm)
\end{equation}
$$

Donde $\hat{g_s}$ y $\hat{\tau_s}$ son el valor permanente de las compras del gobierno en $s$ y el valor permanente de la recaudación del gobierno en $s$, respectivamente. 

##Problema de optimización

El objetivo del agente representativo es,

$$
\max_{c_s, b_{s+1}, s\geq t} \{ \sum_{s \geq t} \beta^{s-t}(\ln(c_s) + v(g_s)): c_s + \tau_s + b_{s+1} = y_s + (1+r_{s-1})b_s, s \geq t \} 
$$

En este problema están dados $\{y_s, r_{s-1}, g_s\}_{s\geq t}$, $b_t$ y $d_t$.

Despejando $\tau_s$ de \@ref(eq:rpgob) y sustituyendo en la restricción presupuestal del agente representativo obtenemos que,

$$
\begin{equation}
c_s + g_s + b_{s+1} - d_{s+1} = y_s + (1+r_{s-1})(b_s - d_s)
(\#eq:rpgobcons)
\end{equation}
$$
Para $s \geq t$. En este caso, la balanza comercial está dada por,

$$
T_s = y_s - c_s - g_s
$$

Y la cuenta corriente está dada por,

$$
CA_s = (b_{s+1} - d_{s+1}) - (b_s - d_s) = T_s + r_{s-1}(b_s -d_s)
$$

##Condiciones de primer orden

A partir de las condiciones de primer orden llegamos a la misma ecuación de euler dado que los impuestos son de suma fija, para cada $s \geq t$,

$$
c_{s+1} = \beta(1 + r_{s})c_s
$$

##Restricción presupuestal

Iterando hacia adelante \@ref(eq:rpgobcons) llegamos a que para cada $s$, en el óptimo, 

$$
\sum_{j \geq s} \Delta_j T_j = -(1 + r_{s-1})(b_s-d_s)
$$
O bien, 

$$
\sum_{j\geq s} \Delta_j c_j = (1 + r_{s-1})(b_s -d_s) + \sum_{j \geq s} \Delta_j y_j - \sum_{j \geq s} \Delta_j g_j
$$

## Solución

Como vimos, a partir de la ecuación de euler se verfifica que para cada $s \geq t$ y cada $j \geq s$,

$$
\Delta_j c_j = \beta^{j-s} \Delta_s c_s
$$
Por lo que, en equilibrio, el valor del consumo en el periodo $s$ está dado por,

$$
c_s = (1-\beta)(1 + r_{s-1})(b_s-d_s) + \hat{y_s} - \hat{g_s}
$$

##Supuestos habituales

Si $r_{s-1} = r^*$ y $\beta(1+r^*) = 1$ entonces,

$$
c_s = r^*(b_s-d_s) + \hat{y_s} - \hat{g_s}
$$
Para cada $s \geq t$. Con esto,

$$
\begin{align}
CA_s &= T_s + r^*(b_s-d_s) \\
&= y_s - c_s - g_s + r^*(b_s-d_s)\\
&= (y_s - \hat{y_s}) - (g_s - \hat{g_s})
\end{align}
$$

##Ejemplo

Supongamos que $r_{s-1} = r^*$, $\beta(1+r^*)=1$, $y_s = y$, $g_s = g$ para cada $s \geq t$ y que $b_t - d_t = 0$. De los primeros dos supuestos obtenemos que el consumo es el mismo en todos los periodos, esto es $c = c_{s+1} = c_s$ para cada $s \geq t$. Del tercer y cuarto supuesto obtenemos que $\hat{y_s} = y$ y $\hat{g_s} = g$ para cada $s \geq t$. Por lo tanto, utilizando el último supuesto, 

$$
c = c_t = (1-\beta)(1+r^*)(b_t-d_t) + \hat{y_t} - \hat{g_t} = y-g
$$
Claramente $T_s = CA_s = 0$ para cada $s \geq t$.

### Choque en el gasto del gobierno 1

Ahora, además de los supuestos anteriores, supongamos que el gobierno eleva sus compras a partir del periodo $t$. Es decir, para cada $s \geq t$ se tiene que $g_s = \lambda g$, con $\lambda > 1$. Denotamos como $c_1$ el consumo durante este choque. Luego, $\hat{g_s} = \lambda g$; por lo tanto,

$$
c_1 = y - \lambda g = c + (1-\lambda)g < c
$$

Es decir, en este caso se reduce el nivel de consumo. Como el choque es permanente se sostiene que $T_s = CA_s = 0$.

### Choque en el gasto del gobierno 2

Ahora supongamos que el choque anterior sucede en sólo un periodo. Es decir, $g_s = \lambda g$ para $\lambda >1$ si $s = t$ y $g_s = g$ si $s \geq t+1$. En este caso, 

$$
\begin{align}
\hat{g_t} &= (1-\beta)\sum_{s\geq t} \beta^{s-t} g_s \\
&=(1-\beta)\left(\lambda g + \sum_{s\geq t+1}\beta^{s-t}g \right) \\
&= (1-\beta)\left(\lambda g + \beta g \sum_{s\geq t+1} \beta^{s-(t+1)}\right) \\
&= (1-\beta)\lambda g + \beta g 
\end{align}
$$

Y $\hat{g_s} = g$ si $s \geq t+1$. Si denotamos $c_2$ el consumo generado por este llegamos a que,

$$
c_2 = y - (1-\beta)\lambda g - \beta g = c + (1-\beta)(1-\lambda)g < c
$$

Dado que el choque es de un periodo, la balanza comercial y la cuenta corriente cambian en el tiempo. Así, en este caso,

$$
\begin{align}
T_t &= y_t - c_t - g_t  \\
&= y - (y - (1-\beta)\lambda g - \beta g) - \lambda g \\
&= \beta (1 - \lambda) g < 0
\end{align}
$$

Por lo que en este periodo se importan bienes. Por otro lado, si $s \geq t+1$ entonces,

$$
\begin{align}
T_s &= y_s - c_s - g_s \\
& = y - (y - (1-\beta)\lambda g - \beta g) - g \\
& = \beta(\lambda - 1)g > 0
\end{align}
$$

Por lo que en estos periodos se exportan bienes. Para la cuenta corriente, recordemos que $b_t - d_t = 0$ por lo que $CA_t = T_t$. Por otro lado, *para encontrar el valor de la deuda externa es necesario establecer supuestos sobre la recaudación*. Supongamos que $\tau_s = \tau$ para cada $s \geq t$ (siempre cobra los mismos impuestos) y que $d_t = 0$. Luego, por \@ref(eq:rpgobperm) se tiene que 

$$
(1-\beta)\lambda g + \beta g = \hat{g_t} = \tau
$$

Así, 

$$
\begin{align}
d_{t+1} &= g_t - \tau_t \\
&= \lambda g - \tau \\
&= \lambda g -(1-\beta)\lambda g - \beta g \\
&= \beta (\lambda -1) g \\
& = -CA_t
\end{align}
$$
Por lo que el gobierno se endeuda en $t$ y $b_{t+1} = 0$. Si por otro lado, el presupuesto es balanceado, es decir $\tau_s = g_s$ para cada $s \geq t$ entonces $d_{t+1} = 0$ y $b_{t+1} = \beta (1- \lambda)g < 0$.

### Choque financiero

Ahora supongamos que la tasa de interés aumenta en el periodo $t$ de forma inesperada. Formalmente, supongamos que $\beta(1+r_s) = \frac{1}{\lambda}$ con $\lambda < 1$ si $s = t$ y $\beta(1+r_{s}) = \beta(1+r^*)=1$ para $s = t-1$ y $s \geq t+1$. Además supongamos que $y_s = y$ y $g_s = g$ para $s \geq t$ y $b_t - d_t < 0$. Bajo estas condiciones, para cualquier $s \geq t+1$ se cumple que

$$
\begin{align}
\Delta_s &= \prod_{k  = t} ^{s-1} \frac{1}{1+r_k} \\
&= \lambda \beta^{s-t}
\end{align}
$$
Por lo tanto,

$$
\begin{align}
\hat{y_t} &= (1-\beta)\sum_{s \geq t} \Delta_s y \\
&= (1-\beta)y(1 + \sum_{s \geq t+1} \lambda \beta^{s-t}) \\
&= (1-\beta)y\left(1 + \frac{\lambda \beta}{1-\beta}\right) \\
&= (1 - \beta)y + \beta \lambda y
\end{align}
$$

Equivalentemente $\hat{g_t} = (1-\beta)g + \beta \lambda g$. Con esto, obtenemos que,

$$
\begin{align}
c_t &= (1-\beta)(1+r_{t-1})(b_t-d_t) + \hat{y_t} - \hat{g_t} \\
&= r^*(b_t-d_t) + (1-\beta)(y-g) + \beta \lambda (y-g)
\end{align}
$$

Denotemos por $c_0$ el valor del consumo en ausencia de choque; es decir, $\lambda = 1$. Luego, $c_0 = r^*(b_t - d_t) + y- g$. Así,

$$
c_t = c_0 + \beta(\lambda - 1)(y-g) < c_0
$$

Tras el choque, se verifica que $c = c_{s+1} = c_s$ para $c \geq t+1$. Usando la ecuación de euler entre $t$ y $t+1$ obtenemos que 

$$
\begin{align}
c &= c_{t+1} \\
&= \beta(1 + r_t)c_t \\
&= \frac{c_t}{\lambda}
\end{align}
$$
La cuenta corriente en $t$ está dada por,

$$
\begin{align}
CA_t &= y- c_t - g + r^*(b_t - d_t) \\
& = y - g - (1-\beta)(y-g) - \beta \lambda (y-g) \\
& = \beta(1-\lambda)(y-g) > 0
\end{align}
$$

<!--chapter:end:02-un-bien-dotacion-gobierno.Rmd-->

#Modelo con un solo bien, dotación y términos de intercambio

## Términos de intercambio

En este modelo se introduce la variable $\Omega_s$ que denota el precio de las exportaciones respecto al precio de las importaciones para cada $s \geq t$. Se supone un país pequeño por lo que la secuencia $\{\Omega_s\}_{s \geq t}$ está dada. 

## Problema de optimización

El objetivo del agente representativo es

$$
\max_{c_s, b_{s+1}, s \geq t} \{ \sum_{s\geq t} \beta^{s-t}\ln(c_s):  c_s + b_{s+1} = \Omega_s y_s + (1+r_{s-1})b_s, s \geq t\}
$$

En este problema están dados $\{y_s, r_{s-1}, \Omega_s\}_{s\geq t}$ y $b_t$. Se asume que $y_s$ se exporta por completo y $c_s$ se importa.
 
Por otro lado, se define

$$
T_s = \Omega_s y_s- c_s
$$
La balanza comercial del país en el periodo $s$ y además

$$
CA_s = b_{s+1} - b_s = T_s + r_{s-1}b_s
$$
La cuenta corriente del país en el periodo $s$. La identidad anterior surge de la restricción presupuestal del agente representativo.  

## Condiciones de primer orden

En este problema se sigue sosteniendo la ecuación de optimalidad de euler. Para cada $s \geq t$,

$$
c_{s+1} = \beta(1 + r_{s})c_s
$$

## Restricción  presupuestal

Iterando hacia adeltante con la restricción presupuestal del agente representativo a partir del periodo $s$ se obtiene que en el óptimo,

$$
\sum_{j\geq s} \Delta_jT_j = -(1+r_{s-1})b_s 
$$
O bien,

$$
\begin{equation}
\sum_{j\geq s} \Delta_jc_j = (1+r_{s-1})b_s  + \sum_{j\geq s} \Delta_j\Omega_j y_j
\end{equation}  
$$

*En particular* para el periodo $t$ se verifica que,

$$
\sum_{s \geq t} \Delta_s c_s = (1+r_{t-1})b_t + \sum_{s \geq t} \Delta_s \Omega_s y_s
$$

## Solución 

Iterando la ecuación de euler como en el capítulo inicial obetenemos que para cada $s \geq t$,

$$
c_s = (1-\beta)(1+r_{s-1})b_s + \widehat{\Omega_s y_s}
$$

Donde $\hat{\Omega_s y_s}$ es el valor permanente de la dotación en términos de las importaciones en el periodo $s$.

## Ejemplo

Los choques en los términos de intercambio son similares a los choques en la dotación.

<!--chapter:end:03-un-bien-dotacion-term-intercambio.Rmd-->

#Modelo con un solo bien, gobierno y producción

En este modelo la cantidad del bien disponible en la economía se produce por lo que $y_s = A_sf(k_s)$ para cada $s \geq t$ y donde $A_s$ es la productividad en el periodo $s$ y $k_s$ es la cantidad de capital en la economía en el periodo $s$. Se asume que no hay depreciación del capital. Además la inversión para cada periodo $s \geq t$ está dada por $i_s = k_{s+1} - k_s$

## Problema de optimización

El agente representativo busca

$$
\max_{c_s,b_{s+1}, k_{s+1}, s \geq t} \{ \sum_{s \geq t} \beta^{s-t}(\ln(c_s) + v(g_s)):c_s + b_{s+1} + \tau_s + k_{s+1}-k_s = A_sf(k_s) + (1+r_{s-1})b_s, s\geq t\}
$$
EL gobierno debe cumplir su restricción presupuestal como lo hemos visto en secciones anteriores. En este problema están dados $\{y_s, r_{s-1}\}_{s\geq t}$, $b_t$, $d_t$ y $k_t$. Introduciendo la restricción presupuestal del gobierno en la del agente representativo y la inversión se obtiene que,

$$
\begin{equation}
c_s + g_s + b_{s+1} - d_{s+1} + i_s = A_sf(k_s) + (1+r_{s-1})(b_s - d_s)
(\#eq:rpcapgob)
\end{equation}
$$
Así, la balanza comercial está dada por,

$$
T_s = A_s f(k_s) - c_s - g_s - i_s
$$
En tanto que la cuenta corriente está dada por,

$$
CA_s = A_sf(k_s) - c_s - g_s -i_s + r_{s-1}(b_s - d_s) = T_s + r_{s-1}(b_s - d_s)
$$


## Condiciones de primer orden

Las condciones de optimalidad de este problema están dadas por

$$
c_{s+1} = \beta(1+r_s)c_s
$$

Para cada $s \geq t$. Y además,

$$
A_{s+1}f'(k_{s+1}) = r_s
$$

##Restricción presupuestal

Iterando la restricción presupuestal \@ref(eq:rpcapgob) a partir de $s$ se obtiene que, en el óptimo, para cada $s \geq t$,

$$
\sum_{j \geq s} \Delta_j T_j = -(1+ r_{s-1})(b_s-d_s)
$$
O bien,

$$
\sum_{j \geq s} \Delta_j c_j = (1 + r_{s-1})(b_s - d_s) + \sum_{j \geq s}\Delta_j(A_j f(k_j) -g_j-i_j) 
$$

*En particular* para el presente se verifica que,

$$
\sum_{s \geq t} \Delta_s c_s = (1 + r_{t-1})(b_t - d_t) + \sum_{s \geq t} \Delta_s (A_sf(k_s) - g_s - i_s)
$$
##Solución

A partir de la ecuación de euler se verifica para cada $s \geq t$ y cada $j \geq s$ lo siguiente,

$$
\Delta_j c_j = \beta^{j-s}\Delta_sc_s
$$
Por lo tanto, para cada $s \geq t$ el consumo está dado por,

$$
c_s = (1-\beta)(1 + r_{s-1})b_s + \widehat{A_sf(k_s)} - \hat{g_s} - \hat{i_s}
$$

El lado derecho de la ecuación anterior es conocida pues a partir de la condición de eficiencia del capital puede conocerce la senda de equilibrio.

##Supuestos habituales

 Si $r_{s-1} = r^*$ para cada $s \geq t$ y $\beta(1 + r^*) = 1$ entonces, por la condición de euler, el consumo es el mismo en todos los periodos y 

$$
c = c_s = r^*(b_s - d_s) + \widehat{A_sf(k_s)} - \hat{g_s} - \hat{i_s}
$$

En este caso, la cuenta corriente está dada por,

$$
CA_s = (A_sf(k_s) - \widehat{A_sf(k_s)}) - (g_s - \hat{g_s})- (i_s - \hat{i_s})
$$

##Ejemplo

Supongamos que $r_{s-1} = r^*$ para cada $s \geq t$, $\beta(1 + r^*) = 1$, $b_t = 0$, $f(k_s) = k_s^{\alpha}$, $g_s = 0$, $A_s = A$ para cada $s \geq t$. Además se supone que el capital inicial cumple con la condición de eficiencia del capital en $t$; es decir, $\alpha Ak_t^{\alpha-1} = r^*$. Como $A$ no cambia en el tiempo, el capital es el mismo para todos los periodos pues la condición de eficiencia señala que $\alpha Ak_{s+1}^{\alpha -1} = r^*$ para $s \geq t+1$. Por lo tanto, $k = k_{s}$ para cada $s \geq t$. Con lo anterior, $i_s = 0$ para cada $s \geq t$ y $A_s f(k_s) = Ak^{\alpha}$ de aquí se verifica que,

$$
c = c_t = A k_t ^{\alpha}
$$

### Choque en la productividad

Apartir de las condiciones anteriores, suponemos un choque positivo en la productividad a partir del periodo $t$ durante $h$ periodos. Formalmente, $A_s = \lambda^{1-\alpha}A$ con $\lambda > 1$ si $t \leq s \leq t+h-1$ y $A_s = A$ si $s \geq t+h$. Además suponemos que el capital inicial cumple con la condición de eficiencia del capital en asuencia de choque, es decir, $\alpha Ak_t^{\alpha-1} = r^*$. Definimos $k_0 = k_t$. Luego, $k_s = k_0$ para $s \geq t+h$ y $k_s = k_1$ para $t \leq s \leq t+h-1$ donde $\alpha \lambda^{1-\alpha}Ak_1^{\alpha-1}$. Luego,

$$
\frac{\alpha Ak_0^{\alpha-1}}{\alpha \lambda^{1-\alpha}Ak_1^{\alpha-1}} = 1
$$

Así,a partir de lo anterior,

$$
(\lambda k_0)^{\alpha-1} = k_1^{\alpha-1}
$$
Por lo que, $k_1 = \lambda k_0$. A partir de esto tenemos tres niveles de producción. Si $s \geq t+h$ entonces,

$$
y_s = Ak_0^{\alpha} = y_0
$$

Por otro lado, si $t+1 \leq s \leq t+h-1$ entonces 

$$
y_s = \lambda^{1-\alpha}Ak_1^\alpha = \lambda Ak_0^{\alpha} = \lambda y_0 = y_1
$$

Por último, $y_t = \lambda^{1-\alpha}y_0$. Con el valor de la producción, tenemos que,

$$
\begin{align}
\hat{y_t} &= (1-\beta)\sum_{s\geq t}\beta^{s-t} y_s \\
&=(1-\beta)\left(\lambda^{1-\alpha}y_0 + \sum_{s = t+1}^{t+h-1}\beta^{s-t}\lambda y_0 + \sum_{s\geq t+h}\beta^{s-t}y_0 \right) \\
&= (1-\beta)\left(\lambda^{1-\alpha}y_0 + \frac{\beta(1-\beta^{h})\lambda y_0}{1-\beta} + \frac{\beta^h y_0}{1-\beta} \right) \\
&= (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^{h-1})\lambda y_0 + \beta^h y_0
\end{align}
$$

Asimismo, se verifica para la inversión que $i_t = k_1 - k_0 = (\lambda-1)k_0$, $i_s = k_{s+1} - k_s = 0$ para $t + 1 \leq s \leq t+h-2$, $i_s = k_{s+1}-k_s = k_0 - k_1 = (1-\lambda)k_0$ si $s = t+h-1$ y por último, $i_s = 0$ en otro caso. Así,

$$
\begin{align}
\hat{i_t} &= (1-\beta) \sum_{s\geq t} \beta^{s-t} i_s \\
&= (1-\beta)\left(i_t + \sum_{s = t+1}^{t+h-2}\beta^{s-t} i_s + \beta^{(t+h-1)-t}i_{t+h-1} + \sum_{s \geq t+h} \beta^{s-t} i_s \right) \\
&= (1-\beta)((\lambda-1)k_0 + \beta^{h-1}(1-\lambda)k_0) \\
&= (1-\beta)(1-\beta^{h-1})(\lambda - 1)k_0
\end{align}
$$
Por lo tanto, el consumo cuando el choque permanece $h$ periodos, denotado por $c_h$, está dado por,

$$
\begin{align}
c_h &= c_t \\
& = \hat{y_t} - \hat{i_t} \\
&= (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^{h-1})\lambda y_0 + \beta^h y_0 - (1-\beta)(1-\beta^{h-1})(\lambda - 1)k_0 
\end{align}
$$
Definamos $c_1$ como el consumo cuando el choque permanece un solo periodo, es decir $h = 1$. Luego,

$$
\begin{align}
c_1 &= (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^0)\lambda y_0 + \beta y_0 - (1-\beta)(1-\beta^{0})(\lambda - 1)k_0  \\
&= (1-\beta)\lambda^{1-\alpha} y_0 + \beta y_0
\end{align}
$$

Definamos, por otro lado, $c_p$ como el consumo cuando el choque es permanente, es decir $h \rightarrow \infty$. Luego, 

$$
\begin{align}
c_p &= \lim_{h \rightarrow \infty}  (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^{h-1})\lambda y_0 + \beta^h y_0 - (1-\beta)(1-\beta^{h-1})(\lambda - 1)k_0 \\
&= (1-\beta)\lambda^{1-\alpha}y_0 + \beta\lambda y_0 - (1-\beta)(\lambda - 1)k_0
\end{align}
$$
Por lo tanto, se verifica que

$$0o, _.nh cx
c_h = (1-\beta^{h-1})c_p + \beta^{h-1}c_1
$$

### Términos de intercambio

Ahora introducimoes los términos de intercambio $\{\Omega_s\}_{s\geq t}$. En este caso el producto en cada periodo está determinado por $\Omega_s A_s f(k_s)$, por lo que la solución es similar a la anterior. Si suponemos que $A_s = 1$ para cada $s \ geq t$ y que hay un choque positivo en los términos de intercammbio, es decir, $\Omega_s = \Omega$ si $s \leq t+1$, $s \geq t+h$ y $\Omega_s = \lambda^{1-\alpha}\Omega$ si $t \leq s \leq t+h-1$. En este caso, el choque es exactamente el mismo que en el caso anterior.

### Senda de crecimiento balanceado

Supongamos que la productividad crece a tasa constante, esto es 

$$
\frac{A_{s+1}}{A_s} = 1 + \hat{A}
$$

Para cada $s \geq t$. Además supongamos que la condición inicial del capital satisface la condición de optimalidad del capital; es decir, $\alpha A_t k_t^{\alpha-1} = r^*$. Este supuesto una implicación fundamental: el capital y la producción crecen a la misma tasa constante. Para verlo, recordemos que para cada $s \geq t+1$ se verifica que en el óptimo, $\alpha A_sk_s^{\alpha-1} = r^*$. A partir del supuesto de la condición inicial del capital, se cumple que para cada $s \geq t$,

$$
\frac{\alpha A_s k_s^{\alpha-1}}{\alpha A_{s+1} k_{s+1}^{\alpha-1}} = 1
$$

Por lo que, 

$$
\frac{k_{s+1}}{k_s} = (1 + \hat{A})^{\frac{1}{1-\alpha}} = 1 + \hat{y}
$$

La producción por otro lado,

$$
\frac{A_{s+1}k_{s+1}^{\alpha}}{A_s k_{s}^{\alpha}} = (1 + \hat{A})^{\frac{1}{1-\alpha}} = 1 + \hat{y}
$$

Lo anterior no es un supuesto del modelo sino un resultado de que la productivdad crezca a una tasa constante. Por otro lado, supongamos que $1+ r_{s-1} = 1+r^* = \beta^{-1}(1+ \hat{y})$ para cada $s \geq t$. En este caso, a partir de la ecuación de euler se verifica que $c_{s+1} = (1+\hat{y})c_s$ para cada $s \geq t$; es decir, el consumo crece a la misma tasa constante que el producto y el capital. Por tanto, para cualquier $s \geq t$,

$$
c_s = (1 + \hat{y})^{s-t}c_t
$$
Del mismo modo, para cada $s \geq t$

$$
y_s = (1 + \hat{y})^{s-t}y_t
$$

Y

$$
i_s = k_{s+1} - k_s = (1+\hat{y})k_s-k_s = (1+\hat{y})^{s-t}\hat{y}k_t = (1+\hat{y})^{s-t}i_t 
$$

Por lo tanto, para cada $s \geq t$,

$$
y_s - i_s = (1 + \hat{y})^{s-t}(y_t-i_t)
$$

Utilizando la ecuación anterior y que $\frac{1+\hat{y}}{1+r^*} = \beta$ se tiene que,

$$
\begin{align}
\hat{y_t} -\hat{i_t} &= (1-\beta)\sum_{s \geq t} \left(\frac{1}{1+r^*}\right)^{s-t}(y_s - i_s) \\
&= (1-\beta)(y_t - i_t)\sum_{s\geq t} \left(\frac{1 + \hat{y}}{1+r^*}\right)^{s-t} \\
&= (1-\beta)(y_t - i_t)\sum_{s\geq t}\beta^{s-t} \\
&= y_t - i_t
\end{align}
$$

Por lo tanto, 

$$
\begin{align}
c_t &= (1-\beta)(1+r^*)b_t + y_t - i_t\\
&=(r^*-\hat{y})b_t + y_t - i_t
\end{align}
$$

La balanza comercial está dada por,

$$
T_s = y_s - c_s - i_s = (1+\hat{y})^{s-t}(y_t-c_t-i_t) = (1+\hat{y})^{s-t}T_t
$$

Con 

$$
T_t = y_t-c_t-i_t = y_t - i_t - (r^*-\hat{y})b_t - (y_t - i_t) = -(r^*-\hat{y})b_t
$$

La cuenta corriente está dada por,

$$
CA_t = T_t + r^*b_t =  -(r^*-\hat{y})b_t + r^* b_t = \hat{y}b_t
$$

Como además $CA_t = b_{t+1} - b_t = \hat{y} b_t$ entonces $b_{s+1} = (1+\hat{y})b_s$ para cada $s \geq t$. De donde se obtiene que 

$$
CA_s = b_{s+1} - b_s = \hat{y}b_s = (1+\hat{y})^{s-t}\hat{y}b_t = (1+\hat{y})^{s-t}CA_t
$$

En particular,

$$
\frac{CA_s}{y_s} = \hat{y} \frac{b_t}{y_t}
$$

#### Depreciación del capital

A partir de las condciones anteriores, supongamos ahora que el capital sufre un choque negativo e inesperado en $t$. Formalmente, $i_s =(\theta + \hat{y})k_s$ si $s = t$ con $\theta \in (0,1)$ y $i_s = (1 + \hat{y})k_s$ para $s \geq t+1$. 

<!--chapter:end:04-un-bien-gobierno-produccion.Rmd-->

# Modelo con dos bienes, dotación

En este caso, la economía posee dos bienes: los comerciales, que denotamos por $T$ y los no comerciables que denotamos por $n$. De esta forma, para cada periodo $s \geq t$ el consumo de bienes comerciales en el periodo $s$ se denota con $c_{Ts}$ y el consumo de bienes no comerciables en el mismo periodo se denota por $c_{ns}$. Además, se define un índice de consumo $c_s$ para cada periodo $s \geq t$ dado por $c_s = c_{Ts}^\gamma c_{ns}^{1-\gamma}$ y $p_s$ como el precio relativo del bien comerciable en términos del no comerciable.

## Problema de optimización

El problema de oprimización del agente representativo es 

$$
\begin{align}
\max_{c_{Ts}, c_{ns}, b_{s+1}, s\geq t}  \sum_{s\geq t} \ln(c_s) \\
 c_s &= c_{Ts}^\gamma c_{ns}^{1-\gamma} \\
c_{Ts} + p_sc_{ns} + b_{t+1} &= y_{Ts} + p_sy_{ns} + (1 + r_{s-1})b_s
\end{align}
$$

En este problema, están dados $\{y_{Ts}, y_{ns}, r_{s-1}\}_{s\geq t}$ y $b_t$. En este caso, $c_{ns} = y_{ns}$ para cada $s \geq t$ ya que estos bienes no se comercian. Por lo tanto, la balanza comercial está dada por,

$$
T_s = y_{T_s} - c_{Ts}
$$
Para cada $s\geq t$. Y la cuenta corriente está dada por,

$$
CA_s = b_{s+1} - b_s = y_{T_s} - c_{Ts} + r_{s-1}b_s = T_s + r_{s-1}b_s
$$
Para cada $s \geq t$. Además, este problema puede dividirse en dos, como lo veremos a continuación.

### Problema de optimización intratemporal

Supongamos que $c_s$ y $p_s$ están fijos para alguna $s \geq t$ arbitraria y fija. Luego, el agente representativo busca encontrar la combinación de bienes que minimice su gasto $c_{Ts} + p_s c_{ns}$. Es decir, el agente busca,

$$
\min_{c_{Ts}, c_{ns}}\{c_{Ts} + p_sc_{ns}: c_s = c_{Ts}^\gamma c_{ns}^{1-\gamma}\}
$$

A partir de la solución, se obtiene la función de gasto óptimo que toma como argumentos $p_s$ y $c_s$, esto es 

$$
e_s = e(p_s,c_s) = \min_{c_{Ts}, c_{ns}}\{c_{Ts} + p_sc_{ns}: c_s = c_{Ts}^\gamma c_{ns}^{1-\gamma}\}
$$ 

En particular, definimos $P_s = e(p_s, 1)$ para cada $s \geq t$, el gasto óptimo cuando el índice de consumo es unitario. Dado que el índice es CD, se cumple que $P_s c_s = e(p_s, c_s)$.

### Problema de optimización intertemporal

Con el problema anterior, ahora el objetivo intertemporal del agente representativo es

$$
\begin{align}
\max_{c_s, s \geq t} \sum_{s \geq t} \ln(c_s) \\
& P_s c_s + b_{t+1} = y_{Ts} + p_s y_{ns} + (1 + r_{s-1})b_s
\end{align}
$$



## Condiciones de primer orden

### Intratemporal

A partir del problema intertemporal se obtiene que, en equilibrio, para cada $s \geq t$,

$$
p_s = \frac{\gamma c_{Ts}}{(1-\gamma)c_{ns}}
$$

Además, con esto se verifica que 

$$
P_s = \frac{1}{\gamma}\left(\frac{\gamma}{1-\gamma}p_s\right)^{1-\gamma }
$$

Con lo anterior, se cumple que $c_{Ts} = \gamma P_s c_s$ y $c_{ns} = (1-\gamma)P_sc_s$.

### Intertemporal

La condición de optimalidad intertemporal obtenida del problema respectivo es, para cada $s \geq t$,

$$
\begin{equation}
P_{s+1}c_{s+1} = \beta(1 + r_s)P_sc_s
(\#eq:optdosb)
\end{equation}
$$

Utilizando el valor de $P_s$ de la sección anterior, obtenemos que,

$$
c_{s+1} = \beta(1+r_s)\left(\frac{p_s}{p_{s+1}}\right)^{1 - \gamma}c_s
$$

### Relación entre las condiciones de optimalidad

ES conveniente identificar la relación exitente entre las condiciones de optimalidad previas. Recordemos que de la condición de eficiencia intratemporal $c_{Ts} = \gamma P_sc_s$. Por lo tanto, sustituyendo en \@ref(eq:optdosb) se tiene que para cada $s \geq t$,

$$
c_{T(s+1)} = \beta(1 +r_{s})c_{Ts}
$$

Recuperamos la ecuación de euler para los bienes comerciables.

## Restricción presupuestal

Dado que $n$ no se comercian, se debe cumplir la siguiente condición de vaciado para cada $s \geq t$, 

$$
c_{ns} = y_{ns}
$$

Por lo tanto, en equilibrio se obtiene que, para cada $s \geq t$, 

$$
\sum_{j \geq s} \Delta_j T_j = -(1+r_{s-1})b_s
$$
O bien,

$$
\sum_{j \geq s}\Delta_j c_{Tj}= (1 + r_{s-1})b_s + \sum_{j\geq s}\Delta_j y_{Tj}
$$

## Solución

Dado que la ecuación de euler se sigue cumpliendo para los bienes comerciables, entonces para cada $s \geq t$, en equilibrio,

$$
c_{Ts} = (1-\beta)(1+r_{s-1})b_s + \widehat{y_{Ts}}
$$
Donde el lado derecho son parámetros conocidos. Además, por la condición de vaciado, para cada $s \geq t$,

$$
c_{ns} = y_{ns}
$$

Donde el lado derecho son parámetros conocidos. Por último, el precio en cada periodo $s \geq t$ queda determinado por,

$$
p_s  = \frac{\gamma c_{Ts}}{(1 - \gamma)c_{ns}}
$$

## Supuestos habituales

Si $r_{s-1} = r^*$ para cada $s \geq t$ y $\beta(1 + r^*) = 1$ entonces, por la condición de euler, el consumo de bienes no comerciables es el mismo en todos los periodos y 

$$
c = c_s = r^*b_s + \widehat{y_{Ts}} 
$$

En este caso, la cuenta corriente está dada por,

$$
CA_s = y_{Ts} - \widehat{y_{Ts}}
$$

## Ejemplo

Supongamos que $r_{s-1} = r^*$ para cada $s \geq t$ y $\beta(1 + r^*) = 1$, $y_{Ts} = y_T$, $y_{ns} = y_n$ para cada $s \geq t$ y además que $b_t = 0$. En este caso, el consumo es el mismo para ambos bienes en todos los periodos y dado que la dotación es constante se verfica que $c_{Ts} = c_T = y_T$, $c_{ns} = c_n = y_n$. Con esto, 

$$
p_s = p = \frac{\gamma c_T}{(1- \gamma)c_n} = \frac{\gamma y_T}{(1- \gamma)y_n}
$$
Finalmente, $T_s = CA_s = 0$, para cada $s \geq t$.

### Choque permanente en bienes comerciables

Supongamos ahora que $y_{Ts} = \lambda y_T$ para cada $s \geq t$. Denotamos como $c_T^p$ el consumo en este choque. Claramente $c_T^p = \lambda y_T$.

### Choque de un periodo en bienes comerciables

A partir de la situación anterior supongamos que hay un choque negativo en la dotación de bienes comerciables. Formalmente, $y_{Ts} = \lambda y_{T}$ si $s = t$ y $y_{Ts} = y_T$ si $s \geq t$. El consumo de bienes no comerciables sigue siendo el mismo. Además se sigue sosteniendo que el consumo de bienes comerciables es el mismo en cada periodo por lo que. Con esta idea en mente, notemos que,

$$
\begin{align}
\widehat{y_{Tt}} &= (1-\beta)\sum_{s\geq t}\beta^{s-t}y_{Ts} \\
&= (1-\beta)\left(\lambda y_T + \sum_{s\geq t+1}\beta^{s-t}y_{T}\right) \\
&= (1-\beta)\left(\lambda y_T + \frac{\beta y_{T}}{1-\beta}\right) \\
&= (1-\beta)\lambda y_T + \beta y_T
\end{align}
$$

Por lo tanto, si denotamos el consumo en este choque como $c_T^1$, se verfica que,

$$
c_{Ts}^1 = c_T^1 = \widehat{y_{Tt}} = (1-\beta)\lambda y_T + \beta y_T < y_T
$$

<!--chapter:end:05-dos-bienes-dotacion.Rmd-->

#Modelo con dos bienes, dotación y gobierno


## Gobierno

En este caso introducimos un gobierno que consume ambos bienes. Denotamos con $g_{Ts}$ la cantidad de bienes comerciables que consume el gobierno en el periodo $s$ y equivalentemente $g_{ns}$ la cantidad de bienes no comerciables que consume el gobierno en el periodo $s$. Luego, el gobierno debe satisfacer la siguiente restricción presupuestal,

$$
g_{Ts} + p_s g_{ns} = p_s \tau_s + b_{s+1} - (1 + r_{s-1})b_s
$$
Para cada $s \geq t$. Iterando hacia adelante a partir del periodo $s$ se obtiene que 

$$
\sum_{j\geq s} \Delta_j (g_{Tj}+p_jg_{nj}) = -(1+r_{s-1})b_s + \sum_{j \geq s} \Delta_j p_j \tau_j
$$


## Problema de optimización

En este caso, el agente representativo busca,

$$
\begin{align}
\max_{c_{Ts}, c_{ns}, b_{s+1}, s\geq t}  \sum_{s\geq t}(\ln(c_s) + \ln(g_s)) \\
 c_s &= c_{Ts}^\gamma c_{ns}^{1-\gamma} \\
c_{Ts} + p_sc_{ns} + p_s \tau_s + b_{t+1} &= y_{Ts} + p_sy_{ns} + (1 + r_{s-1})b_s
\end{align}
$$

En este caso están dados $\{y_{Ts}, y_{ns}, g_{Ts}, g_{ns}, r_{s-1}\}_{s\geq t}$, $d_t$ y $b_T$. Sustituyendo la restricción presupuestal del gobierno en la restricción del agente representativo obtenemos que,

$$
c_{Ts} + p_s c_{ns} + g_{Ts} + p_s g_{ns}+b_{t+1}-d_{t+1} = y_{Ts} + p_sy_{ns}+(1+r_{s-1})(b_s-d_s)
$$
En este caso la condición de vaciado del mercado de bienes no comerciables es

$$
c_{ns} = y_{ns} - g_{ns}
$$
Por lo que la balanza comercial está dada por,

$$
T_s = y_{T_s} - c_{Ts}-g_{Ts}
$$
Y la cuenta corriente está dada por,

$$
CA_s = (b_{s+1}-d_{s+1})-(b_s-d_s) = T_s + r_{s-1}(b_s-d_s)  = y_{T_s} - c_{Ts}-g_{Ts} + r_{s-1}(b_s-d_s)
$$

## Condiciones de primer orden

Las condiciones de optimalidad no sufren ninguna modificación dado que se trata de un impuesto de suma fija. De este modo, se tiene que para cualquier $s \geq t$,

$$
c_{T(s+1)} = \beta(1+r_{s-1})c_{Ts}
$$
Además,

$$
p_s = \frac{\gamma c_{Ts}}{(1-\gamma)c_{ns}}
$$
Y la condición de vaciado,

$$
c_{ns} = y_{ns} - g_{ns}
$$

Para cada $s \geq t$.

## Restricción presupuestal

Considerando la condición de vaciado de mercado e iterando la restricción presupuestal hacia adeltante, resulta que para cada $s\geq t$,

$$
\sum_{j\geq s}\Delta_jT_j = -(1+r_{s-1})(b_s-d_s)
$$

O bien, 

$$
\sum_{j\geq s}\Delta_j c_{Tj} = (1+r_{s-1})(b_s-d_s) + \sum_{j \geq s}\Delta_j (y_{Tj} - g_{Tj})
$$

## Solución

A partir de la ecuación de euler para los bienes comerciables se obtiene que para cada $s \geq t$ y $j \geq s$,

$$
\Delta_j c_{Tj} = \beta^{s-j}c_{Ts}
$$

Por lo tanto, para cada $s \geq t$, 

$$
c_{Ts} = (1-\beta)(1+r_{s-1})(b_s - d_s) + \widehat{y_{Ts}} - \widehat{g_{Tj}}
$$
## Ejemplo

### Dotación del gobierno de bienes comerciables

Hay un caso particular en el que el gobierno posee una dotación de bienes comerciables en todos los periodos, $\{y_s^g\}_{s\geq t}$. Esto se agrega al modelo con $y_s^g = -g_{Ts}$ para cada $s \geq t$ y considerando la senda de impuestos $\{\tau_s\}_{s\geq t}$ como exógena.


<!--chapter:end:06-dos-bienes-dotacion-gobierno.Rmd-->

#Exámenes de parciales

En esta sección se elaboran distintos exámenes parciales de la clase.

## Examen Octubre 2015

## Pregunta 1

Consideremos una economía pequeña y abierta con capital en la que $\beta(1+r_{s-1}) = \beta(1+r^*)$ para cada $s \geq t$. Supongamos que el capital en el periodo $t$ satisface que $Af'(k_t) = r^*$ y además los agentes esperan que la productividad aumenté a $\lambda A$, con $\lambda > 1$ para $t+1 \leq s \leq t+h$, regresando a $A$ a partir $t + h -1$, ¿el valor de $b_{t+h+1}$ es mayor entre ,ás grande sea h?

### Solución 

Como hay dos niveles de productividad, conforme a la condición de optimalidad del capital, habrá dos niveles de capital óptimo. Definimos $k_0$ tal que $Af'(k_0) = r^*$ y $k_1$ tal que $\lambda Af'(k_1) = r^*$. Luego, definiendo $f_0 = f(k_0)$ y $f_1 = f(k_1)$, tenemos que

|$s$|$A_s$  | $k_s$| $y_s$ | $i_s$|
|---|-------|------|-------|-------------------------|
|$t$|$A$  |$k_0$ |$Af_0$ | $k_{t+1}-k_t = 0$ |
|$t+1$|$\lambda A$  |$k_0$ |$\lambda Af_0$ | $k_{t+2}-k_{t+1} = k_1 - k_0$ |
|$t+2$|$\lambda A$  |$k_1$ |$\lambda Af_1$ | $k_{t+3}-k_{t+2} = 0$ |
|$t+h$|$\lambda A$ | $k_1$ |$\lambda Af_1$ | $k_{t+h+1} - k_{t+h} = k_0 - k_1$ |
|$t + h + 1$ | $A$ | $k_0$ | $Af_0$ | $k_{t+h+2}-k_{t+h+1} = 0$ |

Además dado que se cumple la ecuación de euler, el consumo $c$ es el mismo para todos los periodos. Con esto, por un lado,

$$
c = r^*b_t + \hat{y_t} - \hat{i_t}
$$

Y por otro lado,

$$
c = r^* b_{t+h+1} + \widehat{y_{t+h+1}} - \widehat{i_{t+h+1}}
$$
Por lo tanto,

$$
b_{t+h+1} = b_t + \frac{1}{r^*}(\hat{y_t} - \widehat{y_{t+h+1}} - (\hat{i_t} - \widehat{i_{t+h+1}}))
$$
Claramente $\widehat{y_{t+h+1}} = Af_0$ pues a partir de $t+h+1$ la situación vuelve a la normalidad. Lo mismo sucede con $\widehat{i_{t+h+1}} = 0$. Por otro lado,

$$
\begin{align}
\hat{y_t} &= (1-\beta)\sum_{s\geq t}\beta^{s-t}y_s \\
& = (1-\beta)\left(Af_0 + \beta \lambda A f_0 + \sum_{s = t+2}^{t+h}\beta^{s-t}\lambda Af_1 + \sum_{s\geq t+h+1}\beta^{s-t} Af_0\right) \\
&= (1-\beta)\left((1+\beta \lambda)Af_0 + \frac{\beta^2(1-\beta^{h-1})\lambda Af_1}{1-\beta} + \frac{\beta^{h+1}Af_0}{1-\beta}\right) \\
&= ((1-\beta)(1+\beta \lambda) + \beta^{h+1})Af_0 + \beta^2(1-\beta^{h-1})\lambda Af_1
\end{align}
$$

Para la inversión,

$$
\begin{align}
\hat{i_t} &= (1-\beta)\sum_{s\geq t} \beta^{s-t} i_s \\
&=(1-\beta)(\beta(k_1-k_0) + \beta^h (k_0-k_1)) = (1-\beta)\beta(1-\beta^h)(k_1 - k_0)
\end{align}
$$ 
Obsérvese que dados los rendimientos decrecientes a escala de $f$ se verfifica que $k_1 - k_0 > 0$ por lo que $\hat{i_t}<0$. Así,

$$
b_{t+h+1} = b_t + \frac{1}{r^*}(((1-\beta)(1+\beta \lambda) + \beta^{h+1})Af_0 + \beta^2(1-\beta^{h-1})\lambda Af_1 - Af_0- (1-\beta)\beta(1-\beta^h)(k_1 - k_0) )
$$

## Problema 2

Se tiene una economía en la trayectoria de crecimiento balanceado $\frac{A_{S+1}}{A_s} = 1 + \hat{A}$ para cada $s \geq t$, con $b_t = 0$ y se da una destrucción parcial e inesperada de su acervo de capital en el periodo $t$. ¿Eveltualmente la cuenta corriente como la balanza comercial serán negativas?

<!--chapter:end:07-examenes-parciales.Rmd-->

